import { Section } from "./types";

export const sections: Section[] = [
  {
    id: "mental-math",
    name: "Mental Math",
    description: "8 questions, 30 seconds each. Solve in your head!",
    order: 1,
    competition: "math-is-cool",
  },
  {
    id: "individual",
    name: "Individual Contest",
    description: "40 problems, 35 minutes. Questions 1-30 are standard, 31-40 are challenge.",
    order: 2,
    competition: "math-is-cool",
  },
  {
    id: "team-mc",
    name: "Team Multiple Choice",
    description: "10 problems with 5 answer choices each.",
    order: 3,
    competition: "math-is-cool",
  },
  {
    id: "team",
    name: "Team Contest",
    description: "10 problems, 15 minutes. Work together!",
    order: 4,
    competition: "math-is-cool",
  },
  {
    id: "triple-jump",
    name: "Triple Jump",
    description: "10 problems, 15 minutes with 3 submittals at 5/10/15 minutes.",
    order: 5,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-1",
    name: "College Bowl — Round 1",
    description: "10 buzzer-style questions.",
    order: 6,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-2",
    name: "College Bowl — Round 2",
    description: "10 buzzer-style questions.",
    order: 7,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-3",
    name: "College Bowl — Round 3",
    description: "10 buzzer-style questions.",
    order: 8,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-4",
    name: "College Bowl — Round 4",
    description: "10 buzzer-style questions.",
    order: 9,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-5",
    name: "College Bowl — Round 5",
    description: "10 buzzer-style questions.",
    order: 10,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-6",
    name: "College Bowl — Round 6",
    description: "10 buzzer-style questions.",
    order: 11,
    competition: "math-is-cool",
  },
  // MATHCOUNTS sections
  {
    id: "mc-sprint",
    name: "MATHCOUNTS Sprint",
    description: "30 questions, 40 minutes. No calculator allowed.",
    order: 12,
    competition: "mathcounts",
  },
  {
    id: "mc-target",
    name: "MATHCOUNTS Target",
    description: "8 questions in 4 pairs, 6 minutes per pair. Calculator allowed.",
    order: 13,
    competition: "mathcounts",
  },
  {
    id: "mc-team",
    name: "MATHCOUNTS Team",
    description: "10 questions, 20 minutes. Team of 4, calculator allowed.",
    order: 14,
    competition: "mathcounts",
  },
  {
    id: "mc-countdown",
    name: "MATHCOUNTS Countdown",
    description: "Fast-paced oral competition problems.",
    order: 15,
    competition: "mathcounts",
  },
];
