import { Section } from "./types";

export const sections: Section[] = [
  {
    id: "mental-math",
    name: "Mental Math",
    description: "8 questions, 30 seconds each. Solve in your head!",
    order: 1,
    competition: "math-is-cool",
  },
  {
    id: "individual",
    name: "Individual Contest",
    description: "40 problems, 35 minutes. Questions 1-30 are standard, 31-40 are challenge.",
    order: 2,
    competition: "math-is-cool",
  },
  {
    id: "team-mc",
    name: "Team Multiple Choice",
    description: "10 problems with 5 answer choices each.",
    order: 3,
    competition: "math-is-cool",
  },
  {
    id: "team",
    name: "Team Contest",
    description: "10 problems, 15 minutes. Work together!",
    order: 4,
    competition: "math-is-cool",
  },
  {
    id: "triple-jump",
    name: "Triple Jump",
    description: "10 problems, 15 minutes with 3 submittals at 5/10/15 minutes.",
    order: 5,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-1",
    name: "College Bowl — Round 1",
    description: "10 buzzer-style questions.",
    order: 6,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-2",
    name: "College Bowl — Round 2",
    description: "10 buzzer-style questions.",
    order: 7,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-3",
    name: "College Bowl — Round 3",
    description: "10 buzzer-style questions.",
    order: 8,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-4",
    name: "College Bowl — Round 4",
    description: "10 buzzer-style questions.",
    order: 9,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-5",
    name: "College Bowl — Round 5",
    description: "10 buzzer-style questions.",
    order: 10,
    competition: "math-is-cool",
  },
  {
    id: "cb-round-6",
    name: "College Bowl — Round 6",
    description: "10 buzzer-style questions.",
    order: 11,
    competition: "math-is-cool",
  },
  // MATHCOUNTS sections
  {
    id: "mc-sprint",
    name: "MATHCOUNTS Sprint",
    description: "30 questions, 40 minutes. No calculator allowed.",
    order: 12,
    competition: "mathcounts",
  },
  {
    id: "mc-target",
    name: "MATHCOUNTS Target",
    description: "8 questions in 4 pairs, 6 minutes per pair. Calculator allowed.",
    order: 13,
    competition: "mathcounts",
  },
  {
    id: "mc-team",
    name: "MATHCOUNTS Team",
    description: "10 questions, 20 minutes. Team of 4, calculator allowed.",
    order: 14,
    competition: "mathcounts",
  },
  {
    id: "mc-countdown",
    name: "MATHCOUNTS Countdown",
    description: "Fast-paced oral competition problems.",
    order: 15,
    competition: "mathcounts",
  },
  // Olympiad USA sections
  {
    id: "olympiad-dec-2024",
    name: "December 2024",
    description: "Preliminary Round 2 — 35 questions.",
    order: 16,
    competition: "olympiad",
  },
  {
    id: "olympiad-jan-2025",
    name: "January 2025",
    description: "Preliminary Round — 35 questions.",
    order: 17,
    competition: "olympiad",
  },
  // Chapter 5: Conversion of Measurements (Grade 4)
  {
    id: "chp5-length-customary",
    name: "Activity 1: Length in Customary Units",
    description: "Choose the right unit (inch, foot, yard, mile) and estimate lengths.",
    order: 18,
    competition: "chapter-practice",
  },
  {
    id: "chp5-weight-volume-customary",
    name: "Activity 2: Weight & Volume in Customary Units",
    description: "Read scales and choose ounce, pound, ton, cup, pint, quart, or gallon.",
    order: 19,
    competition: "chapter-practice",
  },
  {
    id: "chp5-real-world-customary",
    name: "Activity 3: Real-World Problems (Customary)",
    description: "Solve word problems using customary units of measure.",
    order: 20,
    competition: "chapter-practice",
  },
  {
    id: "chp5-length-metric",
    name: "Activity 4: Length in Metric Units",
    description: "Convert between meters, centimeters, and kilometers.",
    order: 21,
    competition: "chapter-practice",
  },
  {
    id: "chp5-mass-volume-metric",
    name: "Activity 5: Mass & Volume in Metric Units",
    description: "Convert between kilograms/grams and liters/milliliters.",
    order: 22,
    competition: "chapter-practice",
  },
  {
    id: "chp5-real-world-metric",
    name: "Activity 6: Real-World Problems (Metric)",
    description: "Solve word problems using metric units of measure.",
    order: 23,
    competition: "chapter-practice",
  },
  {
    id: "chp5-time",
    name: "Activity 7: Time",
    description: "Convert hours to minutes, minutes to seconds, and use 24-hour clock.",
    order: 24,
    competition: "chapter-practice",
  },
  { id: "chp6-area-unknown-sides", name: "Activity 1: Area and Unknown Sides", description: "Find perimeter and area of rectangles and squares, and solve for unknown sides.", order: 25, competition: "chapter-practice" },
  { id: "chp6-composite-figures", name: "Activity 2: Composite Figures", description: "Find perimeter and area of L-shaped and step-shaped figures.", order: 26, competition: "chapter-practice" },
  { id: "chp6-real-world-area", name: "Activity 3: Real-World Problems", description: "Solve word problems about area and perimeter with borders, paths, and frames.", order: 27, competition: "chapter-practice" },
];
