import { Question } from "../types";

export const mentalMathQuestions: Question[] = [
  {
    id: "mm-1",
    sectionId: "mental-math",
    questionText: "What is the mean of the set of integers from eleven to fifteen inclusive?",
    correctAnswer: "13",
    answerType: "integer",
    explanation: [
      { label: "List the integers", content: "11, 12, 13, 14, 15." },
      { label: "Find the mean", content: "Sum = 65, count = 5, mean = 65 ÷ 5 = 13." },
    ],
    tags: ["statistics"],
    difficulty: "easy",
  },
  {
    id: "mm-2",
    sectionId: "mental-math",
    questionText: "Phoebe and Monica are going to evenly split the cost of a $3,500 car. How many dollars will Phoebe pay for her share of the car?",
    correctAnswer: "1750",
    answerType: "integer",
    explanation: [
      { label: "Split evenly", content: "$3,500 ÷ 2 = $1,750." },
    ],
    tags: ["arithmetic"],
    difficulty: "easy",
  },
  {
    id: "mm-3",
    sectionId: "mental-math",
    questionText: "What is the maximum number of non-overlapping circles of radius 1 cm that can fit inside a 2 cm × 15 cm rectangle?",
    correctAnswer: "7",
    answerType: "integer",
    explanation: [
      { label: "Determine circle size", content: "Each circle has diameter 2 cm, same as the rectangle's height." },
      { label: "Fit along the length", content: "15 ÷ 2 = 7.5, so at most 7 circles fit side by side." },
    ],
    tags: ["geometry"],
    difficulty: "medium",
  },
  {
    id: "mm-4",
    sectionId: "mental-math",
    questionText: "How many prime numbers are between 24 and 32?",
    correctAnswer: "2",
    answerType: "integer",
    explanation: [
      { label: "Check each number", content: "25 (5²), 26 (even), 27 (3³), 28 (even), 29 (prime), 30 (even), 31 (prime)." },
      { label: "Count primes", content: "29 and 31 → 2 prime numbers." },
    ],
    tags: ["number theory"],
    difficulty: "easy",
  },
  {
    id: "mm-5",
    sectionId: "mental-math",
    questionText: "What is three-fourths of 12 plus four-thirds of 12?",
    correctAnswer: "25",
    answerType: "integer",
    explanation: [
      { label: "Compute each part", content: "(3/4) × 12 = 9 and (4/3) × 12 = 16." },
      { label: "Add", content: "9 + 16 = 25." },
    ],
    tags: ["fractions", "arithmetic"],
    difficulty: "easy",
  },
  {
    id: "mm-6",
    sectionId: "mental-math",
    questionText: "Hamta left home for school at 7:30 AM and returned home on the same day at 3:45 PM. How many minutes was Hamta away from home?",
    correctAnswer: "495",
    answerType: "integer",
    explanation: [
      { label: "Calculate hours", content: "7:30 AM to 3:30 PM = 8 hours. Plus 15 more minutes to 3:45 PM." },
      { label: "Convert to minutes", content: "8 × 60 + 15 = 495 minutes." },
    ],
    tags: ["time", "arithmetic"],
    difficulty: "easy",
  },
  {
    id: "mm-7",
    sectionId: "mental-math",
    questionText: "The first three terms of a geometric sequence are 112, 56, and 28. Let term number N be the first term in the sequence that is less than 1. What is N?",
    correctAnswer: "8",
    answerType: "integer",
    explanation: [
      { label: "Find the ratio", content: "Common ratio r = 56/112 = 1/2." },
      { label: "List terms", content: "112, 56, 28, 14, 7, 3.5, 1.75, 0.875. Term 8 (0.875) is the first less than 1." },
    ],
    tags: ["sequences"],
    difficulty: "medium",
  },
  {
    id: "mm-8",
    sectionId: "mental-math",
    questionText: "Min has four standard dice (red, yellow, green, blue). If she rolls them all together, in how many ways can three of the dice show the same number while the fourth die shows something different?",
    correctAnswer: "120",
    answerType: "integer",
    explanation: [
      { label: "Choose the number for three dice", content: "6 choices for the matching number." },
      { label: "Choose which die is different", content: "C(4,1) = 4 ways to pick the odd die out." },
      { label: "Choose the different number", content: "5 remaining numbers for the fourth die." },
      { label: "Multiply", content: "6 × 4 × 5 = 120 ways." },
    ],
    tags: ["combinatorics"],
    difficulty: "hard",
  },
];
