import { Question } from "../types";

export const teamQuestions: Question[] = [
  {
    id: "team-1",
    sectionId: "team",
    questionText: "Evaluate: (3 − 6)³ ÷ (−9) − 17 + ((−5)² − 1)",
    correctAnswer: "10",
    answerType: "integer",
    explanation: [
      { label: "Compute powers", content: "(3−6)³ = (−3)³ = −27. (−5)² = 25." },
      { label: "Evaluate step by step", content: "−27 ÷ (−9) = 3. Then 3 − 17 + (25 − 1) = 3 − 17 + 24 = 10." },
    ],
    tags: ["arithmetic", "order of operations"],
    difficulty: "easy",
  },
  {
    id: "team-2",
    sectionId: "team",
    questionText: "In the 8th grade class of Park Middle School, there are 87 students. One-third have a dog. 23 have a cat and 15 have both a dog and a cat. How many of the 87 students don't have a cat or a dog?",
    correctAnswer: "50",
    answerType: "integer",
    explanation: [
      { label: "Use inclusion-exclusion", content: "Dogs = 87/3 = 29. Cats = 23. Both = 15." },
      { label: "At least one", content: "29 + 23 − 15 = 37 have at least one pet." },
      { label: "Neither", content: "87 − 37 = 50." },
    ],
    tags: ["sets"],
    difficulty: "easy",
  },
  {
    id: "team-3",
    sectionId: "team",
    questionText: "How many positive prime numbers less than 50 have 2 as at least one of their digits?",
    correctAnswer: "3",
    answerType: "integer",
    explanation: [
      { label: "List primes with digit 2", content: "Primes < 50: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47." },
      { label: "Filter for digit 2", content: "2, 23, 29 → 3 primes." },
    ],
    tags: ["number theory"],
    difficulty: "easy",
  },
  {
    id: "team-4",
    sectionId: "team",
    questionText: "As a common fraction, the median of the data set {4/7, 0.6, 5/8, 0.75, 5/12} is A/B. What is A + B?",
    correctAnswer: "8",
    answerType: "integer",
    explanation: [
      { label: "Convert and sort", content: "5/12 ≈ 0.417, 4/7 ≈ 0.571, 0.6 = 3/5, 5/8 = 0.625, 0.75." },
      { label: "Find median", content: "Middle value (3rd of 5) is 0.6 = 3/5. A + B = 3 + 5 = 8." },
    ],
    tags: ["statistics", "fractions"],
    difficulty: "medium",
  },
  {
    id: "team-5",
    sectionId: "team",
    questionText: "Tanishi has $4.37 in coins that consist only of quarters, dimes, nickels, and pennies. She has one nickel among her coins. What is the smallest total number of coins she could have?",
    correctAnswer: "22",
    answerType: "integer",
    explanation: [
      { label: "Use largest coins first", content: "Start with 1 nickel ($0.05). Remaining: $4.32." },
      { label: "Maximize quarters", content: "17 quarters = $4.25. Remaining: $0.07 = 0 dimes + 0 nickels + 7 pennies." },
      { label: "Count", content: "17 + 1 + 7 - but can do better: 17 quarters + 1 nickel + 2 pennies = $4.32 wait. $4.37 - $0.05 = $4.32. 17 quarters = $4.25. $4.32 - $4.25 = $0.07 = 7 pennies. Total: 17 + 1 + 7 = 25. Try: 16 quarters = $4.00. $4.32 - $4.00 = $0.32 = 3 dimes + 2 pennies. Total: 16 + 3 + 1 + 2 = 22." },
    ],
    tags: ["arithmetic", "optimization"],
    difficulty: "medium",
  },
  {
    id: "team-6",
    sectionId: "team",
    questionText: "A particular number series increases alternately by adding 14 and then by multiplying by 1/4. For example, if the first term is 18, the next four terms would be 32, 8, 22, 22/4, and so on. What is the smallest possible integer in the series if the first term is 346?",
    correctAnswer: "5",
    answerType: "integer",
    explanation: [
      { label: "Generate the series", content: "346 → +14 → 360 → ×1/4 → 90 → +14 → 104 → ×1/4 → 26 → +14 → 40 → ×1/4 → 10 → +14 → 24 → ×1/4 → 6 → +14 → 20 → ×1/4 → 5 → +14 → 19 → ×1/4 → 4.75 (not integer)." },
      { label: "Smallest integer", content: "The smallest integer that appears is 5." },
    ],
    tags: ["sequences"],
    difficulty: "hard",
  },
  {
    id: "team-7",
    sectionId: "team",
    questionText: "If N is a perfect cube and a factor of 11!, what is the largest value of N?",
    correctAnswer: "1728",
    answerType: "integer",
    explanation: [
      { label: "Factor 11!", content: "11! = 2⁸ × 3⁴ × 5² × 7 × 11." },
      { label: "Largest cube factor", content: "Take the largest multiple of 3 for each exponent: 2⁶ × 3³ = 64 × 27 = 1728." },
    ],
    tags: ["number theory"],
    difficulty: "hard",
  },
  {
    id: "team-8",
    sectionId: "team",
    questionText: "In a hand of 6 cards there are 2 hearts, 2 diamonds, and 2 clubs. The cards are randomly selected one at a time without replacement and laid on a table. As a reduced common fraction, the probability that the 4th card laid on the table is a heart is A/B. What is A + B?",
    correctAnswer: "4",
    answerType: "integer",
    explanation: [
      { label: "Use symmetry", content: "By symmetry, each card is equally likely to be in any position." },
      { label: "Calculate", content: "P(4th card is a heart) = 2/6 = 1/3. A + B = 1 + 3 = 4." },
    ],
    tags: ["probability"],
    difficulty: "medium",
  },
];
