import { Question } from "../types";

export const tripleJumpQuestions: Question[] = [
  {
    id: "tj-1",
    sectionId: "triple-jump",
    questionText: "Evaluate the following expression when a = 2 and b = 3: 9a²b² + 7ab³",
    correctAnswer: "702",
    answerType: "integer",
    explanation: [
      { label: "Substitute", content: "9(2²)(3²) + 7(2)(3³) = 9(4)(9) + 7(2)(27) = 324 + 378." },
      { label: "Sum", content: "324 + 378 = 702." },
    ],
    tags: ["algebra"],
    difficulty: "easy",
  },
  {
    id: "tj-2",
    sectionId: "triple-jump",
    questionText: "One gallon is equivalent to about 3.78541 liters. To the nearest integer number of milliliters, how many milliliters are in one gallon?",
    correctAnswer: "3785",
    answerType: "integer",
    explanation: [
      { label: "Convert", content: "3.78541 liters × 1000 ml/liter = 3785.41 ml ≈ 3785 ml." },
    ],
    tags: ["unit conversion"],
    difficulty: "easy",
  },
  {
    id: "tj-3",
    sectionId: "triple-jump",
    questionText: "Horace takes 5 minutes to walk one-fifth of a mile home from school. Horace's average rate of walking home from school is A.B miles per hour. What is A + B?",
    correctAnswer: "6",
    answerType: "integer",
    explanation: [
      { label: "Find rate", content: "Distance = 1/5 mile in 5 minutes = 1/12 hour." },
      { label: "Calculate mph", content: "Rate = (1/5) ÷ (1/12) = 12/5 = 2.4 mph. A + B = 2 + 4 = 6." },
    ],
    tags: ["rates"],
    difficulty: "easy",
  },
  {
    id: "tj-4",
    sectionId: "triple-jump",
    questionText: "The first three terms of a geometric sequence are 1458, 486, and 162. What is the 7th term in the sequence?",
    correctAnswer: "2",
    answerType: "integer",
    explanation: [
      { label: "Find ratio", content: "r = 486/1458 = 1/3." },
      { label: "Calculate 7th term", content: "a₇ = 1458 × (1/3)⁶ = 1458/729 = 2." },
    ],
    tags: ["sequences"],
    difficulty: "medium",
  },
  {
    id: "tj-5",
    sectionId: "triple-jump",
    questionText: "A pair of standard dice are rolled. As a reduced common fraction, the probability that the sum of the two numbers showing is greater than 4 and less than 9 is A/B. What is A + B?",
    correctAnswer: "14",
    answerType: "integer",
    explanation: [
      { label: "Count favorable", content: "Sums 5, 6, 7, 8 have 4 + 5 + 6 + 5 = 20 outcomes out of 36." },
      { label: "Simplify", content: "20/36 = 5/9. A + B = 5 + 9 = 14." },
    ],
    tags: ["probability"],
    difficulty: "medium",
  },
  {
    id: "tj-6",
    sectionId: "triple-jump",
    questionText: "A regular hexagon is inscribed in a circle. Given that the area of the hexagon is 294√3 cm², the circumference of the circle can be written as Aπ cm. What is A?",
    correctAnswer: "28",
    answerType: "integer",
    explanation: [
      { label: "Find side length", content: "Area of regular hexagon = (3√3/2)s². So (3√3/2)s² = 294√3 → s² = 196 → s = 14." },
      { label: "Hexagon inscribed in circle", content: "For a regular hexagon inscribed in a circle, s = r. So r = 14." },
      { label: "Circumference", content: "C = 2πr = 28π. A = 28." },
    ],
    tags: ["geometry"],
    difficulty: "hard",
  },
  {
    id: "tj-7",
    sectionId: "triple-jump",
    questionText: "Juana can build a large shed in 5 days less than it takes her brother Carlos. If they built it together it would take them 6 days. How many days would it take Carlos to build the shed by himself?",
    correctAnswer: "15",
    answerType: "integer",
    explanation: [
      { label: "Set up equation", content: "Let Carlos take c days. Juana takes c − 5 days. Combined rate: 1/c + 1/(c−5) = 1/6." },
      { label: "Solve", content: "6(c−5) + 6c = c(c−5) → 6c − 30 + 6c = c² − 5c → c² − 17c + 30 = 0 → (c−15)(c−2) = 0." },
      { label: "Choose valid answer", content: "c = 15 (c = 2 invalid since Juana would take −3 days)." },
    ],
    tags: ["algebra", "rates"],
    difficulty: "hard",
  },
  {
    id: "tj-8",
    sectionId: "triple-jump",
    questionText: "What is the only 7-digit base-7 number in which the first digit tells how many 0s, the second digit tells how many 1s, the third digit tells how many 2s, the fourth digit tells how many 3s, the fifth digit tells how many 4s, the sixth digit tells how many 5s, and the seventh digit tells how many 6s are in the number?",
    correctAnswer: "3211000",
    answerType: "text",
    explanation: [
      { label: "Self-referential puzzle", content: "The number describes its own digit frequencies." },
      { label: "Solution", content: "3211000: three 0s, two 1s, one 2, one 3, zero 4s, zero 5s, zero 6s. Check: digits are 3,2,1,1,0,0,0 → three 0s ✓, two 1s ✓, one 2 ✓, one 3 ✓." },
    ],
    tags: ["logic", "number theory"],
    difficulty: "hard",
  },
];
